local utils = {}

local Colors = {
    ['0'] = "Metalik Siyah",
    ['1'] = "Metalik Graphite Siyah",
    ['2'] = "Metalik Siyah Çelik",
    ['3'] = "Metalik Koyu Gümüş",
    ['4'] = "Metalik Gümüş",
    ['5'] = "Metalik Mavi Gümüş",
    ['6'] = "Metalik Çelik Gri",
    ['7'] = "Metalik Gölge Gümüş",
    ['8'] = "Metalik Taş Gümüş",
    ['9'] = "Metalik Gece Gümüş",
    ['10'] = "Metalik Gun Metal",
    ['11'] = "Metalik Anthracite Gri",
    ['12'] = "Mat Siyah",
    ['13'] = "Mat Gri",
    ['14'] = "Mat Açık Gri",
    ['15'] = "Standart Siyah",
    ['16'] = "Standart Siyah Poly",
    ['17'] = "Standart Koyu silver",
    ['18'] = "Standart Gümüş",
    ['19'] = "Standart Gun Metal",
    ['20'] = "Standart Gölge Gümüş",
    ['21'] = "Eskimiş Siyah",
    ['22'] = "Eskimiş Graphite",
    ['23'] = "Eskimiş Gümüş Gri",
    ['24'] = "Eskimiş Gümüş",
    ['25'] = "Eskimiş Mavi Gümüş",
    ['26'] = "Eskimiş Gölge Gümüş",
    ['27'] = "Metalik Kırmızı",
    ['28'] = "Metalik Torino Kırmızı",
    ['29'] = "Metalik Formula Kırmızı",
    ['30'] = "Metalik Blaze Kırmızı",
    ['31'] = "Metalik Graceful Kırmızı",
    ['32'] = "Metalik Garnet Kırmızı",
    ['33'] = "Metalik Çöl Kırmızı",
    ['34'] = "Metalik Cabernet Kırmızı",
    ['35'] = "Metalik Candy Kırmızı",
    ['36'] = "Metalik Sunrise Turuncu",
    ['37'] = "Metalik Classic Altın",
    ['38'] = "Metalik Turuncu",
    ['39'] = "Mat Kırmızı",
    ['40'] = "Mat Koyu Kırmızı",
    ['41'] = "Mat Turuncu",
    ['42'] = "Mat Sarı",
    ['43'] = "Standart Kırmızı",
    ['44'] = "Standart Parlak Kırmızı",
    ['45'] = "Standart Garnet Kırmızı",
    ['46'] = "Eskimiş Kırmızı",
    ['47'] = "Eskimiş Altınen Kırmızı",
    ['48'] = "Eskimiş Koyu Kırmızı",
    ['49'] = "Metalik Koyu Yeşil",
    ['50'] = "Metalik Racing Yeşil",
    ['51'] = "Metalik Deniz Yeşil",
    ['52'] = "Metalik Olive Yeşil",
    ['53'] = "Metalik Yeşil",
    ['54'] = "Metalik Gasoline Mavi Yeşil",
    ['55'] = "Mat Lime Yeşil",
    ['56'] = "Standart Koyu Yeşil",
    ['57'] = "Standart Yeşil",
    ['58'] = "Eskimiş Koyu Yeşil",
    ['59'] = "Eskimiş Yeşil",
    ['60'] = "Eskimiş Deniz Wash",
    ['61'] = "Metalik Gece Mavi",
    ['62'] = "Metalik Koyu Mavi",
    ['63'] = "Metalik Saxony Mavi",
    ['64'] = "Metalik Mavi",
    ['65'] = "Metalik Mariner Mavi",
    ['66'] = "Metalik Harbor Mavi",
    ['67'] = "Metalik Diamond Mavi",
    ['68'] = "Metalik Surf Mavi",
    ['69'] = "Metalik Nautical Mavi",
    ['70'] = "Metalik Parlak Mavi",
    ['71'] = "Metalik Mor Mavi",
    ['72'] = "Metalik Spinnaker Mavi",
    ['73'] = "Metalik Ultra Mavi",
    ['74'] = "Metalik Parlak Mavi",
    ['75'] = "Standart Koyu Mavi",
    ['76'] = "Standart Gece Mavi",
    ['77'] = "Standart Mavi",
    ['78'] = "Standart Deniz Foam Mavi",
    ['79'] = "Uil Lightning blue",
    ['80'] = "Standart Maui Mavi Poly",
    ['81'] = "Standart Parlak Mavi",
    ['82'] = "Mat Koyu Mavi",
    ['83'] = "Mat Mavi",
    ['84'] = "Mat Gece Mavi",
    ['85'] = "Eskimiş Koyu blue",
    ['86'] = "Eskimiş Mavi",
    ['87'] = "Eskimiş Açık blue",
    ['88'] = "Metalik Taksi Sarı",
    ['89'] = "Metalik Yarış Sarı",
    ['90'] = "Metalik Bronz",
    ['91'] = "Metalik Sarı Bird",
    ['92'] = "Metalik Lime",
    ['93'] = "Metalik Champagne",
    ['94'] = "Metalik Pueblo Beige",
    ['95'] = "Metalik Koyu Ivory",
    ['96'] = "Metalik Choco Kahverengi",
    ['97'] = "Metalik Altınen Kahverengi",
    ['98'] = "Metalik Açık Kahverengi",
    ['99'] = "Metalik Straw Beige",
    ['100'] = "Metalik Moss Kahverengi",
    ['101'] = "Metalik Biston Kahverengi",
    ['102'] = "Metalik Beechwood",
    ['103'] = "Metalik Koyu Beechwood",
    ['104'] = "Metalik Choco Turuncu",
    ['105'] = "Metalik Beach Sand",
    ['106'] = "Metalik Sun Bleeched Sand",
    ['107'] = "Metalik Cream",
    ['108'] = "Standart Kahverengi",
    ['109'] = "Standart Medium Kahverengi",
    ['110'] = "Standart Açık Kahverengi",
    ['111'] = "Metalik Beyaz",
    ['112'] = "Metalik Buzlu Beyaz",
    ['113'] = "Eskimiş Honey Beige",
    ['114'] = "Eskimiş Kahverengi",
    ['115'] = "Eskimiş Koyu Kahverengi",
    ['116'] = "Eskimiş straw beige",
    ['117'] = "Fırçalanmış Çelik",
    ['118'] = "Fırçalanmış Siyah Çelik",
    ['119'] = "Fırçalanmış Aluminium",
    ['120'] = "Krom",
    ['121'] = "Eskimiş Off Beyaz",
    ['122'] = "Standart Off Beyaz",
    ['123'] = "Eskimiş Turuncu",
    ['124'] = "Eskimiş Açık Turuncu",
    ['125'] = "Metalik Securicor Yeşil",
    ['126'] = "Eskimiş Taksi Sarı",
    ['127'] = "Polis Arabası Mavi",
    ['128'] = "Mat Yeşil",
    ['129'] = "Mat Kahverengi",
    ['130'] = "Eskimiş Turuncu",
    ['131'] = "Mat Beyaz",
    ['132'] = "Eskimiş Beyaz",
    ['133'] = "Eskimiş Olive Army Yeşil",
    ['134'] = "Saf Beyaz",
    ['135'] = "Sıcak Pembe",
    ['136'] = "Salmon pink",
    ['137'] = "Metalik Vermillion Pembe",
    ['138'] = "Turuncu",
    ['139'] = "Yeşil",
    ['140'] = "Mavi",
    ['141'] = "Mettalic Siyah Mavi",
    ['142'] = "Metalik Siyah Mor",
    ['143'] = "Metalik Siyah Kırmızı",
    ['144'] = "hunter green",
    ['145'] = "Metalik Mor",
    ['146'] = "Metalik Koyu Mavi",
    ['147'] = "Siyah",
    ['148'] = "Mat Mor",
    ['149'] = "Mat Koyu Mor",
    ['150'] = "Metalik Lava Kırmızı",
    ['151'] = "Mat Forest Yeşil",
    ['152'] = "Mat Olive Drab",
    ['153'] = "Mat Çöl Kahverengi",
    ['154'] = "Mat Çöl Tan",
    ['155'] = "Mat Foilage Yeşil",
    ['156'] = "Varsayılan Alaşım Color",
    ['157'] = "Epsilon Mavi",
    ['158'] = "Saf Altın",
    ['159'] = "Fırçalanmış Altın",
    ['160'] = "MP100"
}

local Classlist = {
    ["0"] = "Kompakt Araçlar",
    ["1"] = "Sedanlar",
    ["2"] = "SUV Araçlar",
    ["3"] = "Coupe Araçlar",
    ["4"] = "Klasik Amerikan",
    ["5"] = "Klasik Spor",
    ["6"] = "Spor Araçlar",
    ["7"] = "Süper Araçlar",
    ["8"] = "Motosikletler",
    ["9"] = "Arazi Araçları",
    ["10"] = "İş Makineleri",
    ["11"] = "Hizmet Araçları",
    ["12"] = "Minibüsler",
    ["13"] = "Bisikletler",
    ["14"] = "Tekneler",
    ["15"] = "Helikopterler",
    ["16"] = "Uçaklar",
    ["17"] = "Servis Araçları",
    ["18"] = "Acil Durum Araçları",
    ["19"] = "Askeri Araçlar",
    ["20"] = "Ticari Araçlar",
    ["21"] = "Trenler",
}

local weaponTable = {
    [584646201]   = "SINIF 2: AP Tabanca",
    [453432689]   = "SINIF 1: Tabanca",
    [3219281620]  = "SINIF 1: Tabanca MK2",
    [1593441988]  = "SINIF 1: Savaş Tabancası",
    [-1716589765] = "SINIF 1: Ağır Tabanca",
    [-1076751822] = "SINIF 1: SNS Tabanca",
    [-771403250]  = "SINIF 2: Çöl Eagle",
    [137902532]   = "SINIF 2: Antika Tabanca",
    [-598887786]  = "SINIF 2: Nişancı Tabancası",
    [-1045183535] = "SINIF 2: Altıpatlar",
    [911657153]   = "Şok Tabancası",
    [324215364]   = "SINIF 2: Mikro SMG",
    [-619010992]  = "SINIF 2: Makineli Tabanca",
    [736523883]   = "SINIF 2: SMG",
    [2024373456]  = "SINIF 2: SMG MK2",
    [-270015777]  = "SINIF 2: Taarruz SMG",
    [171789620]   = "SINIF 2: Savaş PDW",
    [-1660422300] = "SINIF 4: Savaş MG",
    [3686625920]  = "SINIF 4: Savaş MG MK2",
    [1627465347]  = "SINIF 4: Gusenberg",
    [-1121678507] = "SINIF 2: Mini SMG",
    [-1074790547] = "SINIF 3: Taarruz Tüfeği",
    [961495388]   = "SINIF 3: Taarruz Tüfeği MK2",
    [-2084633992] = "SINIF 3: Karabina Tüfek",
    [4208062921]  = "SINIF 3: Karabina Tüfek MK2",
    [-1357824103] = "SINIF 3: Gelişmiş Tüfek",
    [-1063057011] = "SINIF 3: Özel Karabina",
    [2132975508]  = "SINIF 3: Bullpup Tüfek",
    [1649403952]  = "SINIF 3: Kompakt Tüfek",
    [100416529]   = "SINIF 4: Keskin Nişancı Tüfeği",
    [205991906]   = "SINIF 4: Ağır Keskin Nişancı",
    [177293209]   = "SINIF 4: Ağır Keskin Nişancı MK2",
    [-952879014]  = "SINIF 4: Nişancı Tüfeği",
    [487013001]   = "SINIF 2: Pompalı Tüfek",
    [2017895192]  = "SINIF 2: Kesik Namlulu",
    [-1654528753] = "SINIF 3: Bullpup Pompalı",
    [-494615257]  = "SINIF 3: Taarruz Pompalısı",
    [-1466123874] = "SINIF 3: Misket Tüfeği",
    [984333226]   = "SINIF 3: Ağır Pompalı",
    [-275439685]  = "SINIF 2: Çifte Namlulu",
    [317205821]   = "SINIF 2: Otomatik Pompalı",
    [-1568386805] = "SINIF 5: BOMBA ATAR",
    [-1312131151] = "SINIF 5: RPG",
    [125959754]   = "SINIF 5: Kompakt Atar"
}

function utils.GetVehicleClassById(classId)
    return Classlist[tostring(classId)]
end

function utils.GetColor(color)
    return Colors[tostring(color)]
end

function utils.GetVehicleColor(vehicle)
    local vehicleColor1, vehicleColor2 = GetVehicleColours(vehicle)
    local color1 = Colors[tostring(vehicleColor1)]
    local color2 = Colors[tostring(vehicleColor2)]

    if color1 and color2 then return color2 .. " on " .. color1 end

    if color1 then return color1 end

    if color2 then return color2 end

    
    return "Unknown"
end

function utils.GetWeaponName()
    local currentWeapon = GetSelectedPedWeapon(cache.ped)
    return weaponTable[currentWeapon] or "Unknown"
end

return utils